spring:
  data:
    mongodb:
      authentication-database: admin
      username: myuser
      password: mypassword
      database: resumedb
      port: 27017
      host: localhost
  jpa:
    database-platform:
server:
  port : 8081
